// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface BottomFooter {
  logo?: StoryblokAsset;
  description?: string;
  social_links?: SocialLinkItem[];
  navigation_label?: string;
  navigation?: LinkItem[];
  contact_label?: string;
  contacts?: ContactItem[];
  copyright?: StoryblokRichtext;
  component: "bottom_footer";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactForm {
  title?: string;
  description?: string;
  component: "contact_form";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactItem {
  label?: string;
  value?: string;
  icon?: StoryblokAsset;
  link?: string;
  component: "contact_item";
  _uid: string;
  [k: string]: unknown;
}

export interface CtaCard {
  heading?: string;
  section_description?: string;
  title?: string;
  description?: string;
  cta_label?: string;
  cta_link?: string;
  icon?: StoryblokAsset;
  component: "cta_card";
  _uid: string;
  [k: string]: unknown;
}

export interface FeatureCarousel {
  title?: string;
  description?: string;
  cta_label?: string;
  cta_link?: string;
  images?: ImageItem[];
  component: "feature_carousel";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  top?: TopFooter[];
  bottom?: BottomFooter[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface GalleryCarousel {
  title?: string;
  description?: string;
  images?: ImageItem[];
  cta_label?: string;
  cta_link?: string;
  component: "gallery_carousel";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  logo?: StoryblokAsset;
  navigation?: LinkItem[];
  cta_label?: string;
  cta_link?: string;
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface Hero {
  title?: string;
  description?: string;
  background?: StoryblokAsset;
  component: "hero";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageItem {
  image?: StoryblokAsset;
  component: "image_item";
  _uid: string;
  [k: string]: unknown;
}

export interface LinkItem {
  label?: string;
  link?: string;
  sub_links?: LinkItem[];
  component: "link_item";
  _uid: string;
  [k: string]: unknown;
}

export interface ListTestimonials {
  title?: string;
  testimonials?: TestimonialItem[];
  cta_label?: string;
  cta_link?: string;
  variant: "" | "carousel" | "list";
  media?: ImageItem[];
  component: "list_testimonials";
  _uid: string;
  [k: string]: unknown;
}

export interface MessageHighlight {
  tagline?: string;
  title?: string;
  description?: string;
  component: "message_highlight";
  _uid: string;
  [k: string]: unknown;
}

export interface NormalRichtext {
  content?: StoryblokRichtext;
  component: "normal_richtext";
  _uid: string;
  [k: string]: unknown;
}

export interface OfficeHourItem {
  day?: string;
  open_time?: string;
  close_time?: string;
  is_closed?: boolean;
  component: "office_hour_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | CtaCard
    | FeatureCarousel
    | GalleryCarousel
    | Hero
    | ListTestimonials
    | MessageHighlight
    | NormalRichtext
    | ProfileHighlight
    | ServiceOverview
    | ServiceShowcase
    | SplitContent
    | Statistics
    | ContactForm
  )[];
  meta_title?: string;
  meta_description?: string;
  og_image?: StoryblokAsset;
  canonical_url?: string;
  no_index?: boolean;
  seo?: unknown;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface ProfileHighlight {
  tagline?: string;
  heading?: string;
  section_description?: string;
  title?: string;
  description?: StoryblokRichtext;
  image?: StoryblokAsset;
  variant?: "" | "default" | "image_left" | "split_header";
  component: "profile_highlight";
  _uid: string;
  [k: string]: unknown;
}

export interface ServiceItem {
  title?: string;
  description?: string;
  cta_label?: string;
  cta_link?: string;
  image?: StoryblokAsset;
  component: "service_item";
  _uid: string;
  [k: string]: unknown;
}

export interface ServiceOverview {
  title?: string;
  description?: StoryblokRichtext;
  image?: StoryblokAsset;
  component: "service_overview";
  _uid: string;
  [k: string]: unknown;
}

export interface ServiceShowcase {
  title?: string;
  items?: ServiceItem[];
  component: "service_showcase";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialLinkItem {
  icon?: StoryblokAsset;
  link?: string;
  component: "social_link_item";
  _uid: string;
  [k: string]: unknown;
}

export interface SplitContent {
  title?: string;
  description?: StoryblokRichtext;
  image?: StoryblokAsset;
  image_aspect?: string;
  background_image?: StoryblokAsset;
  background_color?: string;
  cta_label?: string;
  cta_link?: string;
  media_position: "" | "left" | "right" | "cover";
  component: "split_content";
  _uid: string;
  [k: string]: unknown;
}

export interface StatisticItem {
  value?: string;
  label?: string;
  icon?: StoryblokAsset;
  component: "statistic_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Statistics {
  title?: string;
  sub_title?: string;
  items?: StatisticItem[];
  component: "statistics";
  _uid: string;
  [k: string]: unknown;
}

export interface TestimonialItem {
  rating?: string;
  content?: string;
  author_name?: string;
  date?: string;
  platform?: "" | "google" | "yelp";
  component: "testimonial_item";
  _uid: string;
  [k: string]: unknown;
}

export interface TopFooter {
  title?: string;
  alternative_title?: string;
  description?: string;
  phone?: string;
  background?: StoryblokAsset;
  office_hours_label?: string;
  office_hours?: OfficeHourItem[];
  cta_label?: string;
  cta_link?: string;
  longitude?: string;
  latitude?: string;
  contacts?: ContactItem[];
  component: "top_footer";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Footer | Header | Page;
